[tool.black]
line-length = 120
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[project]
name = "sympol"
version = "0.3.0"
description = "SYMPOL package"
authors = [
  { name = "Your Name", email = "your.email@example.com" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "jax",
  "chex",
  "flax",
  "distrax",
  "optax",
  "gymnasium",
  "optuna",
  "ray!=2.47.*",
  "ray_utilities[jax,test] @ git+https://github.com/Daraan/ray_utilities",
  "pytest",
  "pytest-timeout",
  "gymnax",
  "graphviz",
]
[project.optional-dependencies]
gymnax = ["gymnax"]
graphviz = ["graphviz"]
optax = ["optax"]
#"tf_keras==2.15.1",
#"tensorflow-probability[tf]==0.23.0",
#"ml_dtypes"

[project.urls]
Homepage = "https://github.com/Daraan/sympol"


[tool.setuptools]
packages = ["sympol"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
  "ARG",
  "RUF",
  "E",
  "F",
  "W",
  "N",
  "PIE",
  "D20",
  "BLE",
  "FBT",
  "B",
  "COM818",
  "C4",
  "T100",
  "FA102",
  "ISC",  # Implicit String Concat
  "ICN",  # Import Conventions
  "LOG",  # logging
  "G",    # Log formatting
  "Q003", "Q004",
  "RET",
  # SLF   # Private member access
  "SLOT", # Reduce memory when using __slots__
  "TID",  # relative | slow imports
  "TC",

  "PERF",
  "FURB",

  "PYI",
  #"PTH",  # Pathlib
  "FIX",  # todo, xxx, fixme

  #"ERA",  # commented out code

  "PD",  # Pandas
  "NPY",  # numpy
  # -- Pylint --
  "PLW",
  "PLE",
  "PLC",
  "PLR",
  "PLR0402", # import A.B as B; from A import B
  "PLR2044",  # empty comment

  "TRY",
]
ignore = [
  "D203", "D205",
  "RET504",  # assignment before return
  "RUF100",  # Unused noqa
  "SIM108",  # Use ternary assignments instead of if blocks
  "SIM300",  # Yoda triggers on GYM_VERSION >= Version("1.0.0")
  "N806", "N812",  # Upercase variables
  "PLR09",  #  Too many

  "TRY003", "TRY400",  # To long error messages, use logging.exception over error

  "PLR2004",  # Magic Values
  "NPY002",  # Use random generator
]
exclude = [
    ".git",
    ".mypy_cache",
    ".tox",
    ".venv",
    "build",
    "dist",
]

[tool.ruff.format]
  docstring-code-format = true
  exclude = [
    ".git",
    "standalone",
  ]

[tool.ruff.lint.per-file-ignores]
"utils/jax_math.py" = [
  "N802" # function name should be snake_case
]

[tool.ruff.lint.isort]
known-first-party = ["ray_utilities"]
force-single-line = false  # default: false

[tool.ruff.lint.pyflakes]
# Avoid F401 error when Generic is not detected
extend-generics = [
    "ray_utilities.setup.experiment_base.ExperimentSetupBase",
    "ray_utilities.setup.ExperimentSetupBase",
    "ray_utilities.jax.jax_model.FlaxRLModel",
    "rllib_port.core.stated_flax_model.StatedCriticFlaxRLModel",
    "rllib_port.core.stated_flax_model.StatedActorFlaxRLModel",
    "ray_utilities.setup.scheduled_tuner_setup.PBTSetup",
    "ray_utilities.setup.scheduled_tuner_setup.MLPPBTSetup",
    "ray_utilities.jax.jax_model.FlaxRLModel",
    "ray_utilities.setup.ppo_mlp_setup.MLPSetup",
    "ray_utilities.setup.ppo_mlp_setup.PPOMLPSetup",
    "ray_utilities.config.DefaultArgumentParser",
    "ray_utilities.config.parser.default_argument_parser.DefaultArgumentParser",
]


[tool.isort]
known_first_party = ["ray_utilities"]
split_on_trailing_comma = true
include_trailing_comma = true
profile = "black"

[tool.pyright]
extraPaths = ["../ray_utilities/"]
exclude = [
  "**/node_modules",
  "**/__pycache__",
  "**/.git/*",
  ".vscode/*",
  "build",
  "dist",
  ".venv",
  "**/outputs/**",
  "standalone",
  "sympol/utils/envs/drawing",
  "**/ppo_gymnax.py",
  "**/ppo_new_interface.py"
]
extends = "ray_utilities/pyproject.toml"
reportDeprecated = "warning"
reportUnnecessaryComparison = "warning"
reportUnnecessaryCast = "warning"
reportPrivateImportUsage = "warning"


[tool.pytest.ini_options]
pythonpath = [
  ".", "rllib_port", "args", "tests",
]
console_output_style = "count"
timeout = 240
session_timeout = 1200
markers = [
   "tuner",
   "basic: Mark tests that should be tested first - if they fail others likely fail",
   "env_runner_cases",
   "length: Mark tests that are fast/medium/slow to execute",
   "flaky: Mark tests as flaky to automatically rerun them on failure",
]
testpaths = [
  "tests"
]
